version: '3.7'

services:
  db:
    image: mariadb:10.3
    restart: always
    container_name: ${P_DOMAIN}-db
    hostname: ${P_DOMAIN}-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${P_USER}
      MYSQL_PASSWORD: ${P_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${P_PASSWORD}
    volumes:
      - /var/docker-data/container/${P_DOMAIN}/mysql:/var/lib/mysql

  nginx:
    image: primehost/wordpress:nginx
    container_name: ${P_DOMAIN}-nginx
    hostname: ${P_DOMAIN}-nginx
    volumes:
      - /var/docker-data/container/${P_DOMAIN}/html:/var/www/html
    environment:
      PRIMEHOST_USER: ${P_USER}
      PRIMEHOST_PASSWORD: ${P_PASSWORD}
      PRIMEHOST_DOMAIN: ${P_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${P_ROUTER}.tls.certresolver=le
      - traefik.http.routers.${P_ROUTER}.entrypoints=websecure
      - traefik.http.services.${P_ROUTER}.loadbalancer.server.port=80
      - traefik.http.routers.${P_ROUTER}.rule=Host(`${P_DOMAIN}`${P_EXTRA_DOMAIN})

  php:
    image: primehost/wordpress:${P_PHP}
    container_name: ${P_DOMAIN}-php
    hostname: ${P_DOMAIN}-php
    depends_on:
      - db
    volumes:
      - /var/docker-data/container/${P_DOMAIN}/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${P_DOMAIN}-db
      WORDPRESS_DB_USER: ${P_USER}
      WORDPRESS_DB_PASSWORD: ${P_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      PRIMEHOST_USER: ${P_USER}
      PRIMEHOST_PASSWORD: ${P_PASSWORD}
      PRIMEHOST_DOMAIN: ${P_DOMAIN}
      LETSENCRYPT_EMAIL: ${P_MAIL}

networks:
  default:
    external:
      name: web
